import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToasterClient } from "@/components/ToasterClient";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import Script from "next/script";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCookie = (await cookies()).get("theme")?.value as undefined | "light" | "dark" | "system";
  const initialDark = themeCookie === "dark" ? true : themeCookie === "light" ? false : undefined;
  return (
    <html lang="en" suppressHydrationWarning className={initialDark ? "dark" : undefined}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* No-flash theme script: sets initial dark class before hydration */}
        {/* Preload minimal colors to avoid white flash on system mode */}
        <Script id="theme-preload-style" strategy="beforeInteractive" dangerouslySetInnerHTML={{
          __html: `try{var s=document.createElement('style');s.id='theme-preload';s.innerHTML='@media (prefers-color-scheme: dark){html:not(.light) body{background:#0b1020;color:#e5e7eb}}@media (prefers-color-scheme: light){html:not(.dark) body{background:#ffffff;color:#0f172a}}';document.head.appendChild(s);}catch{}`
        }} />
        <Script id="theme-noflash" strategy="beforeInteractive" dangerouslySetInnerHTML={{
          __html: `(() => { try {
            const t = localStorage.getItem('theme');
            const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
            const isDark = t === 'dark' || (t === 'system' || !t) && prefersDark;
            const root = document.documentElement;
            if (isDark) root.classList.add('dark'); else root.classList.remove('dark');
          } catch(_){} })();`
        }} />
        <ThemeProvider>
          {children}
          <ToasterClient />
        </ThemeProvider>
      </body>
    </html>
  );
}
